<a href="https://colab.research.google.com/github/Abhilash2240/Probability-Statatics/blob/main/LAB(BASICS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=[1,2,34,6,32,14,65,7]
arr=np.array(a)
print(arr)

[ 1  2 34  6 32 14 65  7]


In [3]:
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)

[ 1  2 34  6 32 14 65  7]


In [4]:
print(arr[0])
print(arr[2])

1
34


In [5]:
aa=[[1,2,3,4],[4,2,3,6]]
A=np.array(aa)
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [6]:
A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)


[[1 2 3 4]
 [4 2 3 6]]


In [7]:
print(type(A))

<class 'numpy.ndarray'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
np.ndim(arr)

1

In [10]:
np.ndim(A)

2

In [11]:
print(np.size(arr))
print(np.size(A))
print(np.shape(arr))
print(np.shape(A))
A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)


8
8
(8,)
(2, 4)
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [12]:
print(A[0,:])
print(A[1,:])
print(A[2,:])
print(A[:,0])
print(A[:,1])
print(A[:,2])
print(A[2,1])
import pandas as pd
Dataset={
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]}
print(Dataset)


[1 2 3]
[3 4 5]
[4 5 6]
[1 3 4]
[2 4 5]
[3 5 6]
5
{'State': ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'], 'Literacy %': [89, 77, 82, 97, 85], 'Avg High Temp(c)': [33, 30, 29, 31, 32]}


In [13]:
df = pd.DataFrame(Dataset)
print(df)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


In [15]:
df = pd.DataFrame({
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]
})
print(df)
print(df.head(2))
print(df.tail(3))
print(df.dtypes)


            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32
            State    Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh  Hyderabad          89                33
1     Maharashtra     Mumbai          77                30
        State     Capital  Literacy %  Avg High Temp(c)
2   Karnataka   Bengaluru          82                29
3      Kerala  Trivandrum          97                31
4  Tamil Nadu     Chennai          85                32
State               object
Capital             object
Literacy %           int64
Avg High Temp(c)     int64
dtype: object


In [16]:
print(df.sort_values('Literacy %', ascending=False))
print(df[['Capital']])
print(df[['State', 'Capital']])
print(df.loc[2])
print(df.iloc[2])


            State     Capital  Literacy %  Avg High Temp(c)
3          Kerala  Trivandrum          97                31
0  Andhra Pradesh   Hyderabad          89                33
4      Tamil Nadu     Chennai          85                32
2       Karnataka   Bengaluru          82                29
1     Maharashtra      Mumbai          77                30
      Capital
0   Hyderabad
1      Mumbai
2   Bengaluru
3  Trivandrum
4     Chennai
            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karnataka   Bengaluru
3          Kerala  Trivandrum
4      Tamil Nadu     Chennai
State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object
State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object


In [18]:
print(df.iloc[1,2])
print(df.loc[1,'Literacy %'])
a={"Distance":[15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16,17, 14, 17, 17, 16, 14, 15, 16, 17, 14, 16, 15, 17, 1]}

import pandas as pd
df=pd.DataFrame(a)
print(df)
print('The number of elements in the column is =',df['Distance'].size)


77
77
    Distance
0         15
1         13
2         16
3         16
4         15
5         16
6         17
7         14
8         15
9         16
10        16
11        17
12        14
13        17
14        17
15        16
16        14
17        15
18        16
19        17
20        14
21        16
22        15
23        17
24         1
The number of elements in the column is = 25


In [19]:
df2=pd.crosstab(index=df['Distance'],columns='Frequency')
print(df2)
print(df2['Frequency'].sum())
df2['Relative_Frequencies']=df2['Frequency']/df2['Frequency'].sum()
df2['Percentage']=df2['Frequency']/df2['Frequency'].sum()*100
print(df2)
df2.loc['Total']=df2.sum()
print(df2)
import numpy as np
import pandas as pd


col_0     Frequency
Distance           
1                 1
13                1
14                4
15                5
16                8
17                6
25
col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
1                 1                  0.04         4.0
13                1                  0.04         4.0
14                4                  0.16        16.0
15                5                  0.20        20.0
16                8                  0.32        32.0
17                6                  0.24        24.0
col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
1               1.0                  0.04         4.0
13              1.0                  0.04         4.0
14              4.0                  0.16        16.0
15              5.0                  0.20        20.0
16              8.0                  0.32        32.0
17              6.0        

In [20]:
import numpy as np
import pandas as pd


In [21]:
data=[328, 470, 405, 375, 298, 326, 276, 362, 410, 255, 391, 370, 455, 229, 300, 183,
283, 366, 400, 495, 215, 157, 374, 306, 280, 409, 321, 269, 398, 200]
diction={"Score":data}
df=pd.DataFrame(diction)
print(df)
A=min(data)
print('The lowest value is ',A)
B=max(data)
print('The highestest value is ',B)
N=round((B-A)/50)
N
bins=np.linspace(150,500,N+1)
print(bins)


    Score
0     328
1     470
2     405
3     375
4     298
5     326
6     276
7     362
8     410
9     255
10    391
11    370
12    455
13    229
14    300
15    183
16    283
17    366
18    400
19    495
20    215
21    157
22    374
23    306
24    280
25    409
26    321
27    269
28    398
29    200
The lowest value is  157
The highestest value is  495
[150. 200. 250. 300. 350. 400. 450. 500.]


In [22]:
df['Class Intervals']=pd.cut(df['Score'],bins=bins,right=False,)
print(df)
table2=pd.crosstab(index=df['Class Intervals'],columns='Frequency')
table2


    Score Class Intervals
0     328  [300.0, 350.0)
1     470  [450.0, 500.0)
2     405  [400.0, 450.0)
3     375  [350.0, 400.0)
4     298  [250.0, 300.0)
5     326  [300.0, 350.0)
6     276  [250.0, 300.0)
7     362  [350.0, 400.0)
8     410  [400.0, 450.0)
9     255  [250.0, 300.0)
10    391  [350.0, 400.0)
11    370  [350.0, 400.0)
12    455  [450.0, 500.0)
13    229  [200.0, 250.0)
14    300  [300.0, 350.0)
15    183  [150.0, 200.0)
16    283  [250.0, 300.0)
17    366  [350.0, 400.0)
18    400  [400.0, 450.0)
19    495  [450.0, 500.0)
20    215  [200.0, 250.0)
21    157  [150.0, 200.0)
22    374  [350.0, 400.0)
23    306  [300.0, 350.0)
24    280  [250.0, 300.0)
25    409  [400.0, 450.0)
26    321  [300.0, 350.0)
27    269  [250.0, 300.0)
28    398  [350.0, 400.0)
29    200  [200.0, 250.0)


col_0            Frequency
Class Intervals           
[150.0, 200.0)           2
[200.0, 250.0)           3
[250.0, 300.0)           6
[300.0, 350.0)           5
[350.0, 400.0)           7
[400.0, 450.0)           4
[450.0, 500.0)           3